import { useEffect, useState, type ReactNode } from "react";
import { DEFAULT_PREFERENCES, MODELS, readStored, type ModelId, type Preferences } from "../../lib/demo";

export default function SettingsPage() {
  const [settings, setSettings] = useState<Preferences>(() => readStored("echogpt-demo-preferences", DEFAULT_PREFERENCES));
  const [saved, setSaved] = useState(false);
  useEffect(() => { document.documentElement.dataset.theme = settings.theme; localStorage.setItem("echogpt-demo-preferences", JSON.stringify(settings)); }, [settings]);
  const change = <K extends keyof Preferences>(key: K, value: Preferences[K]) => { setSettings(current => ({ ...current, [key]: value })); if (key === "defaultModel") localStorage.setItem("echogpt-demo-model", JSON.stringify({ model: value })); setSaved(true); window.setTimeout(() => setSaved(false), 1600); };
  const logout = () => { localStorage.removeItem("echogpt-demo-user"); window.location.href = "/login"; };
  return <div className="settings-shell"><header className="settings-top"><a className="workspace-brand" href="/"><span className="brand-symbol">✳</span> Echo<span>GPT</span></a><nav><a href="/chat">← Back to chat</a><a href="/extension">Extension</a></nav></header><main className="settings-layout"><aside><p className="workspace-eyebrow">WORKSPACE</p><h1>Settings</h1><p>Make EchoGPT feel like your own.</p><div className="settings-side-nav"><a className="selected" href="#general">General</a><a href="#chat-settings">Chat</a><a href="#notifications">Notifications</a><a href="#privacy">Privacy</a><a href="#account">Account</a></div></aside><section className="settings-content"><div className="settings-title"><div><p className="workspace-eyebrow">PREFERENCES</p><h2>Your workspace</h2></div><span className="saved-indicator" aria-live="polite">{saved ? "✓ Saved" : "Saved locally"}</span></div>
    <SettingsSection id="general" title="General" description="Adjust how EchoGPT looks and feels."><div className="setting-row"><div><b>Appearance</b><small>Choose the theme for this device.</small></div><select value={settings.theme} onChange={e => change("theme", e.target.value as Preferences["theme"])} aria-label="Appearance"><option value="light">Light</option><option value="dark">Dark</option></select></div><div className="setting-row"><div><b>Language</b><small>Interface language.</small></div><select value={settings.language} onChange={e => change("language", e.target.value)} aria-label="Language"><option>English</option><option>Tagalog</option><option>Español</option></select></div></SettingsSection>
    <SettingsSection id="chat-settings" title="Chat" description="Set your defaults for new conversations."><div className="setting-row"><div><b>Default AI model</b><small>Used when starting a new chat.</small></div><select value={settings.defaultModel} onChange={e => change("defaultModel", e.target.value as ModelId)} aria-label="Default AI model">{MODELS.map(model => <option key={model.id} value={model.id}>{model.id} · {model.company}</option>)}</select></div><SettingSwitch title="Press Enter to send" description="Use Shift + Enter to add a new line." checked={settings.enterToSend} onChange={value => change("enterToSend", value)}/><SettingSwitch title="Auto-save conversations" description="Keep your demo chats in this browser." checked={settings.autoSave} onChange={value => change("autoSave", value)}/></SettingsSection>
    <SettingsSection id="notifications" title="Notifications" description="Choose which updates you want to hear about."><SettingSwitch title="Email notifications" description="A frontend demo preference. No email will be sent." checked={settings.emailUpdates} onChange={value => change("emailUpdates", value)}/><SettingSwitch title="Product updates" description="Show occasional notes about new features." checked={settings.productUpdates} onChange={value => change("productUpdates", value)}/></SettingsSection>
    <SettingsSection id="privacy" title="Privacy & data" description="Control what stays in this local demo."><SettingSwitch title="Conversation history" description="Save conversations in this browser only." checked={settings.saveHistory} onChange={value => change("saveHistory", value)}/><SettingSwitch title="Page context" description="Allow the extension concept to use page context." checked={settings.pageContext} onChange={value => change("pageContext", value)}/><p className="settings-local-note">Demo data is stored locally in your browser. No production account, cloud sync, or AI provider is connected.</p></SettingsSection>
    <SettingsSection id="account" title="Account" description="Manage this frontend demo session."><div className="account-card"><span className="profile-avatar">A</span><div><b>{localStorage.getItem("echogpt-demo-user") || "Demo workspace"}</b><small>Local demo account · no backend connected</small></div><button onClick={logout}>Log out</button></div></SettingsSection>
    </section></main></div>;
}

function SettingsSection({ id, title, description, children }: { id: string; title: string; description: string; children: ReactNode }) { return <section className="settings-card" id={id}><div className="settings-card-heading"><h3>{title}</h3><p>{description}</p></div><div className="settings-rows">{children}</div></section>; }
function SettingSwitch({ title, description, checked, onChange }: { title: string; description: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="setting-row switch-row"><div><b>{title}</b><small>{description}</small></div><input type="checkbox" role="switch" checked={checked} onChange={event => onChange(event.target.checked)}/></label>; }
